name: crypto_coin_market
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 2.2.3

flutter:
  uses-material-design: true