name: crypto_coin_market
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: 0.12.0+2
  flutter_redux: 0.5.3
  cached_network_image: 1.1.1
  charts_flutter: 0.6.0
  async: 2.3.0
  intl: 0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 3.0.0

flutter:
  uses-material-design: true