name: crypto_coin_market
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.11.3
  flutter_redux: ^0.5.2
  cached_network_image: ^0.4.1
  charts_flutter: ^0.4.0
  async: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 3.0.0

flutter:
  uses-material-design: true